DELETE  http://localhost:8080/events/6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InN1bjJAaG90bWFpbC5jb20iLCJFeHBpcmF0aW9uVGltZSI6MTAwMCwiVXNlcklEIjoyfQ.VweNOyn4XN58qGdaqOsR73L0YojQF883W6hmZLDpBcI